# Generated by Django 4.1 on 2024-01-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "brand",
                    models.CharField(default="", max_length=50, verbose_name="仪器品牌"),
                ),
                ("time", models.DateTimeField(verbose_name="引进时间")),
                (
                    "num",
                    models.CharField(default="", max_length=50, verbose_name="仪器型号"),
                ),
                (
                    "function",
                    models.CharField(default="", max_length=1050, verbose_name="功能用途"),
                ),
                (
                    "book",
                    models.CharField(default=0, max_length=10, verbose_name="预约方式"),
                ),
                (
                    "status",
                    models.CharField(default="", max_length=20, verbose_name="仪器状态"),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="仪器图片")),
                (
                    "research",
                    models.CharField(default="", max_length=20, verbose_name="支撑课题"),
                ),
                (
                    "para",
                    models.CharField(default=0, max_length=30, verbose_name="关键参数"),
                ),
                (
                    "detail",
                    models.CharField(default="", max_length=20, verbose_name="关键配件"),
                ),
                (
                    "locate",
                    models.CharField(default="", max_length=20, verbose_name="仪器所在地"),
                ),
            ],
        ),
    ]
