# Generated by Django 4.1 on 2024-01-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="classic",
            field=models.CharField(default="", max_length=20, verbose_name="设备分类"),
        ),
        migrations.AddField(
            model_name="item",
            name="lab",
            field=models.CharField(default="", max_length=20, verbose_name="负责科室"),
        ),
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(default="", max_length=20, verbose_name="设备名称"),
        ),
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(default="", max_length=30, verbose_name="仪器品牌"),
        ),
        migrations.AlterField(
            model_name="item",
            name="function",
            field=models.CharField(default="", max_length=100, verbose_name="功能用途"),
        ),
    ]
