# Generated by Django 4.1 on 2024-01-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0002_item_classic_item_lab_item_name_alter_item_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="city",
            field=models.CharField(default="", max_length=8, verbose_name="城市"),
        ),
        migrations.AlterField(
            model_name="item",
            name="function",
            field=models.CharField(default="", max_length=300, verbose_name="功能用途"),
        ),
        migrations.AlterField(
            model_name="item",
            name="para",
            field=models.CharField(default=0, max_length=300, verbose_name="关键参数"),
        ),
    ]
