# Generated by Django 4.1 on 2024-01-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0003_item_city_alter_item_function_alter_item_para"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="detail",
            field=models.CharField(default="", max_length=100, verbose_name="关键配件"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="设备图片"),
        ),
        migrations.AlterField(
            model_name="item",
            name="locate",
            field=models.CharField(default="", max_length=20, verbose_name="设备所在地"),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(default="", max_length=20, verbose_name="设备状态"),
        ),
    ]
