# Generated by Django 4.1 on 2024-01-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0004_alter_item_detail_alter_item_image_alter_item_locate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="para",
            field=models.CharField(default=0, max_length=500, verbose_name="关键参数"),
        ),
    ]
