# Generated by Django 4.1 on 2024-01-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0005_alter_item_para"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="book",
            field=models.CharField(default="线上", max_length=10, verbose_name="预约方式"),
        ),
        migrations.AlterField(
            model_name="item",
            name="classic",
            field=models.CharField(default="其他设备", max_length=20, verbose_name="设备分类"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.IntegerField(default=0, verbose_name="设备图片"),
        ),
        migrations.AlterField(
            model_name="item",
            name="para",
            field=models.CharField(default="", max_length=500, verbose_name="关键参数"),
        ),
    ]
