# Generated by Django 4.1 on 2024-01-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0006_alter_item_book_alter_item_classic_alter_item_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.CharField(default=0, max_length=5, verbose_name="设备图片"),
        ),
    ]
