# Generated by Django 4.1 on 2024-01-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0007_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.IntegerField(default=0, verbose_name="设备图片"),
        ),
    ]
