# Generated by Django 4.1 on 2024-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0009_item_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="contact",
            field=models.CharField(default="", max_length=60, verbose_name="联系方式"),
        ),
    ]
