# Generated by Django 4.1 on 2024-01-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rent", "0010_item_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.IntegerField(default="0", max_length=60, verbose_name="价格"),
        ),
    ]
